path: /media/bharath/drive/Personal_Learning/object-detection-yolov8-custom-data/data ## always use absolute path
train: images/train # train dir relative path
val: images/val # validation dir relative path

# classes

names:
  0: alpaca